server:
  mode: debug
  port: :8080
  jwtkey: hellogo

mysql:
  host: localhost
  port: 3306
  user: root
  password: 123456
  name: ggblog

qiniu:
  accesskey: 0Kpw-ItaVA9JTa1ZMiloRUqYRt5Bcof_dOGbbdP9
  secretkey: YaNc-e7DlmtYzQL_SuMDLT5XWGn-VLO_dW_Psbku
  bucket: ggbloglian
  server: http://sefzgm5p6.hd-bkt.clouddn.com/